version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: "lab-credentials:DOCKER_USERNAME"  
    DOCKER_PASSWORD: "lab-credentials:DOCKER_PASSWORD"  

phases:
  pre_build:
    commands:
     - echo "Logging in to DockerHub "
     - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build:
    commands:
     - echo "Building backend Docker image"
      # Build Docker image cho backend
     - docker build -t myapp-backend:latest backend-python/

     - echo "Building frontend Docker image"
      # Build Docker image cho frontend
     - docker build -t myapp-frontend:latest frontend-react/

  post_build:
    commands:
     - echo "Pushing Docker images to DockerHub"
      # Push Docker images lên DockerHub
     - docker push myapp-backend:latest
     - docker push myapp-frontend:latest

artifacts:
  files:
    - '**/*'