version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: "lab-credentials:DOCKER_USERNAME"  # Lấy username từ secret
    DOCKER_PASSWORD: "lab-credentials:DOCKER_PASSWORD"  # Lấy password

phases:
  install:
    commands:
      - echo "Checking if Docker is installed and running..."
      - command -v docker || echo "Docker not found"  # In ra thông báo nếu Docker không được tìm thấy
      - if ! command -v docker &> /dev/null; then echo "Docker is not installed, installing now..." && exit 1; fi  # Dừng nếu Docker không tìm thấy
      - echo "Installing Docker..."
      - sudo apt-get update -y  # Cập nhật hệ thống Ubuntu
      - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common  # Cài đặt các gói phụ trợ
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -  # Thêm khóa GPG của Docker
      - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"  # Thêm kho lưu trữ Docker vào apt
      - sudo apt-get update -y  # Cập nhật lại danh sách gói
      - sudo apt-get install -y docker-ce  # Cài đặt Docker Community Edition
      - sudo systemctl start docker  # Khởi động dịch vụ Docker
      - sudo usermod -aG docker $USER  # Thêm người dùng vào nhóm docker

  pre_build:
    commands:
      - echo "Docker is installed. Proceeding with login..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin  # Đăng nhập Docker Hub
      - echo "Using latest tag for images"

  build:
    commands:
      - echo "Building Docker image with latest tag..."
      - docker build -t myapp-backend:latest backend-python/.  # Build backend image
      - docker build -t myapp-frontend:latest frontend-react/.  # Build frontend image

  post_build:
    commands:
      - echo "Running Docker containers on EC2 instance..."
      - docker stop myapp-backend || true && docker rm myapp-backend || true
      - docker stop myapp-frontend || true && docker rm myapp-frontend || true
      - docker run -d --name myapp-backend -p 5000:5000 myapp-backend:latest
      - docker run -d --name myapp-frontend -p 3000:3000 myapp-frontend:latest
      - echo "Docker containers are now running."

artifacts:
  files:
    - "**/*"