version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: "lab_credentials:DOCKER_USERNAME"  # Lấy username từ secret
    DOCKER_PASSWORD: "lab_credentials:DOCKER_PASSWORD"  # Lấy password

phases:
  install:
    runtime-versions:
      python: 3.8  
    commands:
      - echo "Checking if Docker is installed and running..."
      - if ! command -v docker &> /dev/null; then echo "Docker is not installed, exiting." && exit 1; fi
      - echo "Installing Docker..."
      - amazon-linux-extras install docker -y
      - service docker start
      - usermod -a -G docker ec2-user

  pre_build:
    commands:
      - echo "Docker is installed. Proceeding with login..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin  # Đăng nhập Docker Hub để chuẩn bị build và push image
      - export VERSION_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Using version tag:$VERSION_TAG"
  build:
    commands:
      - echo "Building Docker image with version tag $VERSION_TAG..."
      - docker build -t myapp-backend:$VERSION_TAG  backend-python/. 
      - docker build -t myapp-frontend:$VERSION_TAG  frontend-python/. # Đường dẫn tới backend
      - docker tag myapp-backend:$VERSION_TAG myapp-backend:latest
      - docker tag myapp-frontend:$VERSION_TAG myapp-frontend:latest

  post_build:
    commands:
      - echo "Running Docker containers on EC2 instance..."
      - docker stop myapp-backend || true && docker rm myapp-backend || true
      - docker stop myapp-frontend || true && docker rm myapp-frontend || true
      - docker run -d --name myapp-backend -p 5000:5000 myapp-backend:latest
      - docker run -d --name myapp-frontend -p 3000:3000 myapp-frontend:latest
      - echo "Docker containers are now running."


artifacts:
  files:
    - "**/*"

